{% set name = "pytest-socket" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: af9bb5f487da72be63573a6194cfac033b6c7a1c1561e150521105970f9e99f2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - pytest >=6.2.5
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - pytest_socket
  commands:
    - python -m pip check

about:
  home: https://github.com/miketheman/pytest-socket
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Pytest Plugin to disable socket calls during tests
  description: |
    A plugin to use with Pytest to disable or restrict socket calls
    during tests to ensure network calls are prevented.

extra:
  recipe-maintainers:
    - duncanmmacleod
